[package]
name = "blinksy"
version = "0.1.0"
edition = "2021"

[dependencies]
defmt = "0.3.10"
embedded-hal = "1.0.0"
fugit = "0.3.7"
heapless = "0.8.0"
palette = { version = "0.7.6", default-features = false, features = ["libm", "bytemuck"] }
